import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { MemoryRouter } from "react-router-dom";
import { AuthContext } from "@/features/auth/context/AuthContext";
import { InstitutionListPage } from "../InstitutionListPage";
const auth:any={token:"token",user:null,activeRoles:[],login:vi.fn(),logout:vi.fn(),isLoading:false};
const institution={id:1,nombre:"Escuela Uno",codigo:"UE1",ruc:"1",fecha_creacion:"",fecha_actualizacion:null,autoridades_academicas:[]};
const page=(overrides={})=>({count:11,next:"next",previous:"previous",results:[institution],...overrides});
const ok=(data:any,status=200)=>({ok:true,status,json:async()=>data} as Response); const fail=(data:any,status=400)=>({ok:false,status,json:async()=>data} as Response);
function mount(){return render(<MemoryRouter><AuthContext.Provider value={auth}><InstitutionListPage/></AuthContext.Provider></MemoryRouter>)}
describe("institution administration interactions",()=>{
 beforeEach(()=>{vi.stubGlobal("confirm",vi.fn(()=>true));vi.stubGlobal("fetch",vi.fn().mockResolvedValue(ok(page())))})
 it("submits search and toggles every ordering field in both directions",async()=>{mount();await screen.findByText("Escuela Uno");fireEvent.change(screen.getByLabelText("Buscar instituciones"),{target:{value:"Loma"}});fireEvent.submit(screen.getByLabelText("Buscar instituciones").closest("form")!);await waitFor(()=>expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining("nombre=Loma"),expect.anything()));for(const label of ["Nombre de la institución","Código","RUC"]){fireEvent.click(screen.getByRole("button",{name:new RegExp(label)}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.length).toBeGreaterThan(1));fireEvent.click(screen.getByRole("button",{name:new RegExp(label)}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.length).toBeGreaterThan(2))}const urls=vi.mocked(fetch).mock.calls.map(call=>String(call[0]));for(const field of ["nombre","codigo","ruc"]){expect(urls.some(url=>url.includes(`ordering=${field}`))).toBe(true);expect(urls.some(url=>url.includes(`ordering=-${field}`)||url.includes(`ordering=%2D${field}`))).toBe(true)}});
 it("uses pagination envelope next and previous",async()=>{mount();await screen.findByText(/1 registros de 11/);fireEvent.click(screen.getByRole("button",{name:"Siguiente"}));await waitFor(()=>expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining("page=2"),expect.anything()));fireEvent.click(screen.getByRole("button",{name:"Anterior"}));await waitFor(()=>expect(fetch).toHaveBeenLastCalledWith(expect.stringContaining("page=1"),expect.anything()))});
  it("creates and edits a user-entered required code, then confirms deletion",async()=>{mount();await screen.findByText("Escuela Uno");fireEvent.click(screen.getByText("Nueva institución"));const createCode=screen.getByLabelText("Código de institución");expect(createCode).toBeRequired();fireEvent.change(createCode,{target:{value:"NUEVA-01"}});for(const [label,value] of [["nombre","Nueva"],["ruc","9"]] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});fireEvent.click(screen.getByRole("button",{name:"Guardar"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith("/api/instituciones/",expect.objectContaining({method:"POST",body:JSON.stringify({codigo:"NUEVA-01",nombre:"Nueva",ruc:"9"})})));fireEvent.click(screen.getByRole("button",{name:"Editar Escuela Uno"}));const editCode=screen.getByLabelText("Código de institución");expect(editCode).toHaveValue("UE1");fireEvent.change(editCode,{target:{value:"UE2"}});fireEvent.click(screen.getByRole("button",{name:"Guardar"}));await waitFor(()=>expect(fetch).toHaveBeenCalledWith("/api/instituciones/1/",expect.objectContaining({method:"PATCH",body:JSON.stringify({codigo:"UE2",nombre:"Escuela Uno",ruc:"1"})})));fireEvent.click(screen.getByRole("button",{name:"Eliminar Escuela Uno"}));await waitFor(()=>expect(confirm).toHaveBeenCalled());expect(fetch).toHaveBeenCalledWith("/api/instituciones/1/",expect.objectContaining({method:"DELETE"}))});
 it("renders loading and fetch errors",async()=>{vi.mocked(fetch).mockImplementationOnce(()=>new Promise(()=>{}));mount();expect(await screen.findByText("Cargando instituciones…")).toBeInTheDocument()});
 it("loads empty assignments and role catalog and closes accessible focused modal with Escape",async()=>{mount();await screen.findByText("Escuela Uno");vi.mocked(fetch).mockResolvedValueOnce(ok([])).mockResolvedValueOnce(ok([{id:77,nombre:"AUTORIDAD_ACADEMICA"}]));fireEvent.click(screen.getByText("Gestionar"));const dialog=await screen.findByRole("dialog",{name:/Autoridades académicas/});expect(dialog.querySelector("section")).toHaveFocus();fireEvent.keyDown(document,{key:"Escape"});await waitFor(()=>expect(screen.queryByRole("dialog",{name:/Autoridades académicas/})).not.toBeInTheDocument())});
  it("shows backend duplicate and required code field errors",async()=>{mount();await screen.findByText("Escuela Uno");fireEvent.click(screen.getByText("Nueva institución"));for(const [label,value] of [["Código de institución","DUP-01"],["nombre","Nueva"],["ruc","9"]] as const)fireEvent.change(screen.getByLabelText(label),{target:{value}});vi.mocked(fetch).mockResolvedValueOnce(fail({codigo:["Este código ya existe."]}));fireEvent.click(screen.getByRole("button",{name:"Guardar"}));expect(await screen.findByText("Este código ya existe.")).toBeInTheDocument();fireEvent.change(screen.getByRole("textbox",{name:/Código de institución/}),{target:{value:""}});vi.mocked(fetch).mockResolvedValueOnce(fail({codigo:["Este campo es obligatorio."]}));fireEvent.submit(screen.getByRole("button",{name:"Guardar"}).closest("form")!);expect(await screen.findByText("Este campo es obligatorio.")).toBeInTheDocument()});
  it("shows a stable fallback when institution deletion is rejected",async()=>{const unhandled=vi.fn();window.addEventListener("unhandledrejection",unhandled);mount();await screen.findByText("Escuela Uno");vi.mocked(fetch).mockRejectedValueOnce(new Error("Network unavailable"));fireEvent.click(screen.getByRole("button",{name:"Eliminar Escuela Uno"}));expect(await screen.findByRole("status")).toHaveTextContent("No se pudo eliminar la institución.");await Promise.resolve();expect(unhandled).not.toHaveBeenCalled();window.removeEventListener("unhandledrejection",unhandled)});
 });
