import { useEffect,useRef,useState } from "react"; import { ROLE_ACADEMIC_AUTHORITY } from "@/config/app"; import { assignmentApi } from "../services/api"; import type { ApiErrors,Authority,Institution,UserOption } from "../types/institucionTypes";
export function AuthorityModal({institution,token,onClose,onMutate}:{institution:Institution;token:string;onClose:()=>void;onMutate:()=>Promise<void>}){
 const dialog=useRef<HTMLElement>(null); const [items,setItems]=useState<Authority[]>([]),[users,setUsers]=useState<UserOption[]>([]),[editing,setEditing]=useState<Authority|null>(null),[adding,setAdding]=useState(false),[userId,setUserId]=useState(""),[errors,setErrors]=useState<ApiErrors>({}),[roleId,setRoleId]=useState<number|null>(null);
 const load=async()=>{try{const [assignments,roles]=await Promise.all([assignmentApi.list(token,institution.id),assignmentApi.roles(token)]);setItems(assignments);setRoleId(roles.find(role=>role.nombre===ROLE_ACADEMIC_AUTHORITY)?.id??null)}catch{setErrors({detail:["No se pudieron cargar las autoridades académicas."]})}}; useEffect(()=>{void load()},[]); useEffect(()=>{dialog.current?.focus();const close=(event:KeyboardEvent)=>event.key==="Escape"&&onClose();document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close)},[onClose]);
 async function begin(item?:Authority){setEditing(item??null);setAdding(true);setUserId(item?String(item.usuario.id):"");try{setUsers(await assignmentApi.users(token,!item))}catch{setErrors({detail:["No se pudieron cargar los usuarios."]})}}
 async function save(){try{const role=roleId;if(!role){setErrors({rol:["No se encontró AUTORIDAD_ACADEMICA en el catálogo de roles."]});return} const data={usuario:Number(userId),rol:role,institucion:institution.id}; editing?await assignmentApi.update(token,editing.id,data):await assignmentApi.create(token,data);setAdding(false);await load();await onMutate()}catch(e){setErrors((e as {data:ApiErrors}).data??{})}}
 async function mutate(action:()=>Promise<unknown>){try{setErrors({});await action();await load();await onMutate()}catch(e){setErrors((e as {data:ApiErrors}).data??{detail:["No se pudo actualizar la asignación."]})}}
 return <div role="dialog" aria-modal="true" aria-labelledby="authority-title" className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4"><section ref={dialog} tabIndex={-1} className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded bg-surface p-6"><div className="flex justify-between"><h2 id="authority-title" className="text-xl font-bold">Autoridades académicas — {institution.nombre}</h2><button aria-label="Cerrar" onClick={onClose}><span aria-hidden="true" className="material-symbols-outlined">close</span></button></div><button className="my-4 rounded bg-primary px-4 py-2 text-white" onClick={()=>void begin()}>Agregar autoridad</button>{Object.values(errors).flat().map(x=><p role="alert" className="text-danger" key={x}>{x}</p>)}{adding&&<div className="mb-4 rounded border p-4"><label>Usuario<select aria-label="Usuario" value={userId} onChange={e=>setUserId(e.target.value)} className="ml-2 border p-2"><option value="">Seleccione</option>{users.map(u=><option key={u.id} value={u.id}>{u.first_name} {u.last_name} ({u.username})</option>)}</select></label><button onClick={()=>void save()} className="ml-3 bg-success px-3 py-2 text-white">Guardar</button></div>}<ul className="divide-y">{items.map(a=><li key={a.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><span>{a.usuario.first_name} {a.usuario.last_name} — {a.es_activo?"Activa":"Inactiva"}</span><span className="flex gap-2"><button onClick={()=>void begin(a)}>Editar</button><button onClick={()=>void mutate(()=>assignmentApi.state(token,a.id,!a.es_activo))}>{a.es_activo?"Desactivar":"Activar"}</button><button onClick={()=>confirm("¿Eliminar esta asignación?")&&void mutate(()=>assignmentApi.remove(token,a.id))} className="text-danger">Eliminar</button></span></li>)}</ul></section></div>
}
