import { useState, type FormEvent } from "react";
import type { ApiErrors, Institution, InstitutionInput } from "../types/institucionTypes";

export function InstitutionForm({institution,onCancel,onSave}:{institution?:Institution;onCancel:()=>void;onSave:(data:InstitutionInput)=>Promise<void>}){
 const [values,setValues]=useState<InstitutionInput>({codigo:institution?.codigo??"",nombre:institution?.nombre??"",ruc:institution?.ruc??""}); const [errors,setErrors]=useState<ApiErrors>({});
 async function submit(e:FormEvent){e.preventDefault();const trimmed={codigo:values.codigo.trim(),nombre:values.nombre.trim(),ruc:values.ruc.trim()};try{await onSave(trimmed)}catch(error){setErrors((error as {data?:ApiErrors}).data??{})}}
 const maxLengths:Record<"codigo"|"nombre"|"ruc",number>={codigo:20,nombre:200,ruc:20};
 return <div role="dialog" aria-modal="true" aria-labelledby="institution-title" className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4"><form onSubmit={submit} className="w-full max-w-lg rounded bg-surface p-6 shadow-xl"><h2 id="institution-title" className="text-xl font-bold">{institution?"Editar institución":"Nueva institución"}</h2>{([["codigo","Código de institución"],["nombre","nombre"],["ruc","ruc"]] as const).map(([field,label])=><label key={field} className="mt-4 block font-medium"><span className="capitalize after:ml-1 after:text-danger after:content-['*']">{label}</span><input required aria-required="true" pattern=".*\S.*" title="Este campo es obligatorio y no puede contener solo espacios." maxLength={maxLengths[field]} value={values[field]} onChange={e=>setValues({...values,[field]:e.target.value})} className="mt-1 w-full rounded border border-input-border p-3"/>{errors[field]?.map(x=><span role="alert" className="block text-sm text-danger" key={x}>{x}</span>)}</label>)}{errors.non_field_errors?.map(x=><p role="alert" className="text-danger" key={x}>{x}</p>)}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel}>Cancelar</button><button className="rounded bg-primary px-5 py-2 text-white">Guardar</button></div></form></div>
}
