# Generated by Django 4.2.30 on 2026-07-13 15:17

from django.db import migrations, models
import django.db.models.deletion

PLANNING_TABLES = (
    "organizacion_educacionnivel",
    "organizacion_educacionsubnivel",
    "organizacion_planestudio",
    "organizacion_gradoescolar",
    "organizacion_asignatura",
)


def preserve_existing_planning_tables(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    with schema_editor.connection.cursor() as cursor:
        for table in PLANNING_TABLES:
            if table in existing_tables:
                legacy_table = f"{table}_legacy_0004"
                cursor.execute(f'ALTER TABLE "{table}" RENAME TO "{legacy_table}"')
                cursor.execute(f'PRAGMA index_list("{legacy_table}")')
                indexes = [row[1] for row in cursor.fetchall() if not row[1].startswith("sqlite_autoindex_")]
                for index in indexes:
                    cursor.execute(f'DROP INDEX "{index}"')


def restore_existing_planning_data(apps, schema_editor):
    existing_tables = set(schema_editor.connection.introspection.table_names())
    if "organizacion_educacionnivel_legacy_0004" not in existing_tables:
        return

    statements = (
        """INSERT INTO organizacion_educacionnivel
            (id, fecha_creacion, fecha_actualizacion, nombre, pp_minutos, pp_semana_minimo)
            SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, nombre, 40,
                   MAX(1, carga_horaria_minima_semanal)
            FROM organizacion_educacionnivel_legacy_0004""",
        """INSERT INTO organizacion_educacionsubnivel
            (id, fecha_creacion, fecha_actualizacion, nombre, pp_semana_minimo, educacion_nivel_id)
            SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, nombre,
                   MAX(1, carga_horaria_minima_semanal), nivel_id
            FROM organizacion_educacionsubnivel_legacy_0004""",
        """INSERT INTO organizacion_planestudio
            (id, es_activo, fecha_creacion, fecha_actualizacion, nombre, institucion_id)
            SELECT id,
                   CASE WHEN es_activo AND ROW_NUMBER() OVER (
                       PARTITION BY institucion_id, es_activo ORDER BY id
                   ) = 1 THEN 1 ELSE 0 END,
                   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, nombre, institucion_id
            FROM organizacion_planestudio_legacy_0004""",
        """INSERT INTO organizacion_gradoescolar
            (id, fecha_creacion, fecha_actualizacion, nombre, orden, nivel_id, plan_estudio_id, subnivel_id)
            SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, nombre,
                   ROW_NUMBER() OVER (PARTITION BY plan_estudio_id ORDER BY orden, id),
                   nivel_id, plan_estudio_id, subnivel_id
            FROM organizacion_gradoescolar_legacy_0004""",
        """INSERT INTO organizacion_asignatura
            (id, fecha_creacion, fecha_actualizacion, nombre, pp_semana_minimo, grado_escolar_id)
            SELECT id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, nombre,
                   MAX(1, carga_horaria_semanal), grado_id
            FROM organizacion_asignatura_legacy_0004""",
    )
    with schema_editor.connection.cursor() as cursor:
        for statement in statements:
            cursor.execute(statement)
        for table in reversed(PLANNING_TABLES):
            cursor.execute(f'DROP TABLE "{table}_legacy_0004"')



class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_align_teacher_schema'),
    ]

    operations = [
        migrations.RunPython(
            preserve_existing_planning_tables,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=150)),
                ('pp_semana_minimo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EducacionNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pp_minutos', models.PositiveIntegerField()),
                ('pp_semana_minimo', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'nivel educativo',
                'verbose_name_plural': 'niveles educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EducacionSubnivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pp_semana_minimo', models.PositiveIntegerField()),
                ('educacion_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subniveles', to='organizacion.educacionnivel')),
            ],
            options={
                'verbose_name': 'subnivel educativo',
                'verbose_name_plural': 'subniveles educativos',
                'ordering': ['educacion_nivel_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlanEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_activo', models.BooleanField(default=False)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=200)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes_estudio', to='organizacion.institucion')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GradoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados_escolares', to='organizacion.educacionnivel')),
                ('plan_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados_escolares', to='organizacion.planestudio')),
                ('subnivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grados_escolares', to='organizacion.educacionsubnivel')),
            ],
            options={
                'verbose_name': 'grado escolar',
                'verbose_name_plural': 'grados escolares',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='educacionnivel',
            constraint=models.CheckConstraint(check=models.Q(('pp_minutos__gt', 0)), name='nivel_pp_minutos_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='educacionnivel',
            constraint=models.CheckConstraint(check=models.Q(('pp_semana_minimo__gt', 0)), name='nivel_pp_semana_gt_0'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='grado_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='organizacion.gradoescolar'),
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(fields=('institucion', 'nombre'), name='plan_nombre_por_institucion_uniq'),
        ),
        migrations.AddConstraint(
            model_name='planestudio',
            constraint=models.UniqueConstraint(condition=models.Q(('es_activo', True)), fields=('institucion',), name='plan_activo_por_institucion_uniq'),
        ),
        migrations.AddConstraint(
            model_name='gradoescolar',
            constraint=models.CheckConstraint(check=models.Q(('orden__gt', 0)), name='grado_orden_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='gradoescolar',
            constraint=models.UniqueConstraint(fields=('plan_estudio', 'nombre'), name='grado_nombre_por_plan_uniq'),
        ),
        migrations.AddConstraint(
            model_name='educacionsubnivel',
            constraint=models.CheckConstraint(check=models.Q(('pp_semana_minimo__gt', 0)), name='subnivel_pp_semana_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='educacionsubnivel',
            constraint=models.UniqueConstraint(fields=('educacion_nivel', 'nombre'), name='subnivel_nombre_por_nivel_uniq'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.CheckConstraint(check=models.Q(('pp_semana_minimo__gt', 0)), name='asignatura_pp_semana_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='asignatura',
            constraint=models.UniqueConstraint(fields=('grado_escolar', 'nombre'), name='asignatura_nombre_por_grado_uniq'),
        ),
        migrations.RunPython(
            restore_existing_planning_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
